### PR TITLE
Set resource total size to content size when using a qrc:// resource

### LINKED ISSUE #1065: libraries/networking/src/ResourceCache.cpp:515: void ResourceCache::updateTotalSize(const qint64&): Assertion `_totalResourcesSize >= 0' failed.
## Problem

This is a failure of a sanity check in ResourceCache.cpp:

    511	void ResourceCache::updateTotalSize(const qint64& deltaSize) {
    512	   _totalResourcesSize += deltaSize;
    513	
    514	   // Sanity checks
    515	   assert(_totalResourcesSize >= 0);
    516	   assert(_totalResourcesSize < (1024 * BYTES_PER_GIGABYTES));

`deltaSize` is 0 and `_totalResourcesSize` is 0.

This happens from Resource::setSize(0), which comes from `ResourceCache.cpp:797` in `Resource::handleReplyFinished`.

The URL being requested seems to be `qrc:///meshes/keyboard/SM_enter.fbx`. This is interesting, because that should exist, `result` is `Resource::Request::Success`, and `_request->getData()` returns a bunch of binary stuff starting with `$20 = "Kaydara FBX Binary  \000\032\000 \034` -- seems to have worked. However `_bytesTotal`, the argument to `setSize` is 0.

`_bytesTotal` gets updated in `Resource::handleDownloadProgress`.

### Hypothesis:

`Resource::handleDownloadProgress` may never get called for things that are in `qrc://` and therefore not actually downloaded. This results in a `_bytesTotal` of 0. Once this percolates down to `ResourceCache::updateTotalSize`, if nothing else has added to `_totalResourcesSize` before, an assertion is triggered.

### Possible fix

Set `_bytesTotal` to `_request.getData().length()` in such cases? The file on disk is 33248 bytes, which matches what I get from that call.

## Backtrace

```
#0  0x00007fffe619a9d5 in raise () from /lib64/libc.so.6
#1  0x00007fffe61838a4 in abort () from /lib64/libc.so.6
#2  0x00007fffe6183789 in __assert_fail_base.cold () from /lib64/libc.so.6
#3  0x00007fffe6193026 in __assert_fail () from /lib64/libc.so.6
#4  0x00007fffe7a9535e in ResourceCache::updateTotalSize (this=0x2964150, deltaSize=@0x7fffffff9e80: 0)
    at /home/dale/Vircadia/source/libraries/networking/src/ResourceCache.cpp:515
#5  0x00007fffe7aa3816 in QtPrivate::FunctorCall<QtPrivate::IndexesList<0>, QtPrivate::List<long long>, void, void (ResourceCache::*)(long long const&)>::call
    (f=(void (ResourceCache::*)(ResourceCache * const, const long long &)) 0x7fffe7a95300 <ResourceCache::updateTotalSize(long long const&)>, o=0x2964150, 
    arg=0x7fffffff9e90) at /home/dale/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:152
#6  0x00007fffe7aa3014 in QtPrivate::FunctionPointer<void (ResourceCache::*)(long long const&)>::call<QtPrivate::List<long long>, void> (f=
    (void (ResourceCache::*)(ResourceCache * const, const long long &)) 0x7fffe7a95300 <ResourceCache::updateTotalSize(long long const&)>, o=0x2964150, 
    arg=0x7fffffff9e90) at /home/dale/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:185
#7  0x00007fffe7aa1d9b in QtPrivate::QSlotObject<void (ResourceCache::*)(long long const&), QtPrivate::List<long long>, void>::impl (which=1, 
    this_=0x7ffeedc11ec0, r=0x2964150, a=0x7fffffff9e90, ret=0x0) at /home/dale/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:418
#8  0x00007fffe693f993 in ?? () from /home/dale/Vircadia/install_master/interface/../../qt5-install/lib/libQt5Core.so.5
#9  0x00007fffe7989a43 in Resource::updateSize (this=0x7ffeec093370, _t1=0)
    at /home/dale/Vircadia/build/libraries/networking/networking_autogen/UVLADIE3JM/moc_ResourceCache.cpp:970
#10 0x00007fffe7a966c7 in Resource::setSize (this=0x7ffeec093370, bytes=@0x7ffeec0933e0: 0)
    at /home/dale/Vircadia/source/libraries/networking/src/ResourceCache.cpp:730
#11 0x00007fffe7a9765b in Resource::handleReplyFinished (this=0x7ffeec093370) at /home/dale/Vircadia/source/libraries/networking/src/ResourceCache.cpp:797
#12 0x00007fffe7aa3ad2 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (Resource::*)()>::call(void (Resource::*)(), Resource*, void**) (f=(void (Resource::*)(Resource * const)) 0x7fffe7a97106 <Resource::handleReplyFinished()>, o=0x7ffeec093370, arg=0x7ffd5c2aa098)
    at /home/dale/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:152
#13 0x00007fffe7aa3314 in QtPrivate::FunctionPointer<void (Resource::*)()>::call<QtPrivate::List<>, void>(void (Resource::*)(), Resource*, void**) (
    f=(void (Resource::*)(Resource * const)) 0x7fffe7a97106 <Resource::handleReplyFinished()>, o=0x7ffeec093370, arg=0x7ffd5c2aa098)
    at /home/dale/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:185
#14 0x00007fffe7aa277f in QtPrivate::QSlotObject<void (Resource::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x242e4290, r=0x7ffeec093370, a=0x7ffd5c2aa098, ret=0x0) at /home/dale/Vircadia/qt5-install/include/QtCore/qobjectdefs_impl.h:418
#15 0x00007fffe6937eb9 in QObject::event(QEvent*) () from /home/dale/Vircadia/install_master/interface/../../qt5-install/lib/libQt5Core.so.5
#16 0x00007ffff42d162f in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /home/dale/Vircadia/install_master/interface/../../qt5-install/lib/libQt5Widgets.so.5
#17 0x00007ffff42da2c0 in QApplication::notify(QObject*, QEvent*) ()
   from /home/dale/Vircadia/install_master/interface/../../qt5-install/lib/libQt5Widgets.so.5

#18 0x00000000009fde06 in Application::notify (this=0x7fffffffa730, object=0x7ffeec093370, event=0x7ffd5c2aa050)
--Type <RET> for more, q to quit, c to continue without paging--
    at /home/dale/Vircadia/source/interface/src/Application.cpp:4246
#19 0x00007fffe690c9e2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /home/dale/Vircadia/install_master/interface/../../qt5-install/lib/libQt5Core.so.5
#20 0x00007fffe690f024 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /home/dale/Vircadia/install_master/interface/../../qt5-install/lib/libQt5Core.so.5
#21 0x00007fffe6961113 in ?? () from /home/dale/Vircadia/install_master/interface/../../qt5-install/lib/libQt5Core.so.5
#22 0x00007fffe5daf96f in g_main_dispatch (context=0x1a10d60) at ../glib/gmain.c:3325
#23 g_main_context_dispatch (context=0x1a10d60) at ../glib/gmain.c:4043
#24 0x00007fffe5e01758 in g_main_context_iterate.constprop.0 (context=context@entry=0x1a10d60, block=block@entry=1, dispatch=dispatch@entry=1, 
    self=<optimized out>) at ../glib/gmain.c:4119
#25 0x00007fffe5dacd43 in g_main_context_iteration (context=0x1a10d60, may_block=1) at ../glib/gmain.c:4184
#26 0x00007fffe69607ee in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/dale/Vircadia/install_master/interface/../../qt5-install/lib/libQt5Core.so.5
#27 0x00007fffe690b6fb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/dale/Vircadia/install_master/interface/../../qt5-install/lib/libQt5Core.so.5
#28 0x00007fffe6912fce in QCoreApplication::exec() () from /home/dale/Vircadia/install_master/interface/../../qt5-install/lib/libQt5Core.so.5
#29 0x0000000000cf0fca in main (argc=1, argv=0x7fffffffdd48) at /home/dale/Vircadia/source/interface/src/main.cpp:448
```

### PR DESCRIPTION
**Pull request by daleglass**
When a Resource is requested from qrc://, the Resource::handleDownloadProgress
event is never called, and therefore _bytesTotal remains at zero. This confuses
ResourceCache later, which has a sanity check that doesn't pass when resources
are retrieved, yet no data accumulates.

Fixes #1065

### CODE REVIEW

File: libraries/networking/src/ResourceCache.cpp [hunk 1]
```diff
@@ -809,6 +807,14 @@ void Resource::handleReplyFinished() {
         }
 
         auto data = _request->getData();
+        if (_request->getUrl().scheme() == "qrc") {
```
Comment (daleglass) [inline libraries/networking/src/ResourceCache.cpp:810]: I'm not entirely sure if this check is necessary. It may be perfectly safe to do it always

File: libraries/networking/src/ResourceCache.cpp [hunk 2]
```diff
@@ -809,6 +807,14 @@ void Resource::handleReplyFinished() {
...
+            // For resources under qrc://, there's no actual download being done, so
+            // handleDownloadProgress never gets called. We get the full length here
+            // at the end.
+            _bytesTotal = data.length();
+        }
+
+        setSize(_bytesTotal);
```
Comment (daleglass) [inline libraries/networking/src/ResourceCache.cpp:817]: Note we're not calling setSize in the case of failure anymore. 

I think this should be fine since on failure no data arrives, and this can cause confusion in ResourceCache.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1068/Vircadia-PR1068-3feec6f-_b102b347.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1068/Vircadia-PR1068-3feec6f-.tar_b102b347.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1068/Vircadia-PR1068-3feec6f-.tar_b102b347.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1068/Vircadia-PR1068-3feec6f-_b102b347.sh

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1068/Vircadia-PR1068-3feec6f-_b102b347.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1068/Vircadia-PR1068-3feec6f_b102b347.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1068/Vircadia-Quest-Alpha-PR1068-3feec6f_b102b347.apk

**Comment by digisomni** [comment]
What might be a good way to test this to confirm it works?

**Review by ctrlaltdavid — APPROVED** [review]

**Review by digisomni — APPROVED** [review]
The tutorial and Hub worked fine with this PR.
