### PR TITLE
Fix HIFI_MEMORY_DEBUGGING on Linux/gcc

### LINKED ISSUE #1119: Building with HIFI_MEMORY_DEBUGGING doesn't work
It builds, but the resulting application doesn't run:

    $ interface/interface
    ==31730==Your application is linked against incompatible ASan runtimes.

This is weird, interface links against the library:

    $ ldd interface/interface | grep -i asan
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f0ada161000)

And nothing seems to link against another one:

```
for lib in `ldd interface/interface | awk '{print $3}'` ; do ldd $lib  |grep -i asan ; done                                  1 
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f42f3de2000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f2256f2d000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f10a4e12000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f8079580000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007fb30ca75000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f39e4cb8000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007fe3fc865000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f3400ae5000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007fd0585a6000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f01d614a000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f8468d04000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f87325be000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007fce61bd5000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f68ff470000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007fcb3f210000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f2e098e0000)
	libasan.so.6 => /lib64/libasan.so.6 (0x00007f05f3468000)
```

### PR DESCRIPTION
**Pull request by daleglass**
It seems that libasan was running into some sort of trouble due to static linking.

Additionally, `-fstack-protector-strong` has been enabled by disabling the usage of the `FIR_1x4_AVX512` function under memory debugging. This should provide additional protection against stack smashing.

Testing:
* `export VIRCADIA_MEMORY_DEBUGGING=1`
* build on Linux. OSX may also work, but the build probably takes the clang path there, which wasn't changed in this PR. Windows isn't supported yet.
* Verify that the interface starts (before it wouldn't). 
* With this enabled, you should see additional errors in the log from the additional sanitizer checks, such as:
`vircadia-master/libraries/entities-renderer/src/RenderableGridEntityItem.cpp:53:9: runtime error: load of value 190, which is not a valid value for type 'bool'`
* The interface crashing with an error such as this is an acceptable outcome. It means the sanitizer is working and found something to fix:
`==306449==ERROR: AddressSanitizer: stack-buffer-overflow on address 0x7ffc102c4640 at pc 0x7f7957533f19 bp 0x7f78651ba030 sp 0x7f78651ba028`
* Noticeably lower performance is a very expected side-effect of doing additional checking.

Fixes #1119

### CODE REVIEW

File: libraries/audio/src/AudioHRTF.cpp [hunk 1]
```diff
@@ -91,8 +91,8 @@ static const float azimuthTable[NAZIMUTH][3] = {
 // A first-order shelving filter is used to minimize the disturbance in ITD.
 //
 // Loosely based on data from S. Spagnol, "Distance rendering and perception of nearby virtual sound sources
-// with a near-field filter model,� Applied Acoustics (2017)
```
Comment (daleglass) [inline libraries/audio/src/AudioHRTF.cpp:94]: This here is unrelated to the PR, but VSCode wasn't saving it correctly, so I had to get rid of it.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-5ae1e2a-.tar_5ffc05f7.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-5ae1e2a-.tar_5ffc05f7.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-5ae1e2a-_5ffc05f7.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-5ae1e2a-_5ffc05f7.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-5ae1e2a-_5ffc05f7.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-5ae1e2a_5ffc05f7.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-Quest-Alpha-PR1127-5ae1e2a_5ffc05f7.apk

**Comment by daleglass** [comment]
Added some minor improvements and planning for a follow-up thread debugging PR.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-da17740-.tar_c02c38bf.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-da17740-_c02c38bf.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-da17740-.tar_c02c38bf.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-da17740-_c02c38bf.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-da17740_c02c38bf.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-Quest-Alpha-PR1127-da17740_c02c38bf.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-da17740-_c02c38bf.exe

File: libraries/audio/src/AudioHRTF.cpp [hunk 2]
```diff
@@ -388,7 +388,12 @@ void crossfade_4x2_AVX2(float* src, float* dst, const float* win, int numFrames)
 void interpolate_AVX2(const float* src0, const float* src1, float* dst, float frac, float gain);
 
 static void FIR_1x4(float* src, float* dst0, float* dst1, float* dst2, float* dst3, float coef[4][HRTF_TAPS], int numFrames) {
+#ifndef STACK_PROTECTOR
+    // Enabling -fstack-protector on gcc causes an undefined reference to FIR_1x4_AVX512 here
     static auto f = cpuSupportsAVX512() ? FIR_1x4_AVX512 : (cpuSupportsAVX2() ? FIR_1x4_AVX2 : FIR_1x4_SSE);
+#else
+    static auto f = cpuSupportsAVX2() ? FIR_1x4_AVX2 : FIR_1x4_SSE;
+#endif
```
Comment (JulianGro) [inline libraries/audio/src/AudioHRTF.cpp:396]: This part of the code is a bit too much for me.
My understanding is that you are disabling AVX512 support when `-fstack-protector` is not in use (which it isn't). So you are just future proofing in case someone gets `-fstack-protector` to work.

Comment (daleglass) [reply libraries/audio/src/AudioHRTF.cpp:396]: No, it's the reverse. Enabling memory debugging enables -fstack-protector-strong, which breaks FIR_1x4_AVX512 for some reason. So this ensures that function isn't used in that case.

The original hifi code just disabled fstack-protector instead, but it could be useful for debugging since it's an additional check.

**Review by JulianGro — APPROVED** [review]
I haven't tested it, but the code looks good.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-f43eb0d-_7e914796.dmg

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-f43eb0d-_7e914796.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-f43eb0d-.tar_7e914796.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-f43eb0d-.tar_7e914796.gz

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-f43eb0d-_7e914796.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-f43eb0d-_7e914796.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-PR1127-f43eb0d_7e914796.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1127/Vircadia-Quest-Alpha-PR1127-f43eb0d_7e914796.apk

**Comment by JulianGro** [comment]
Testing is fine.
When giving no value, it builds without memory debugging.
When giving `false` it builds without memory debugging.
When giving `true` it builds with memory debugging and shows everything fine in console.
