### PR TITLE
Text Entity alignment property

### LINKED ISSUE #206: Add "center text" option to Text entities

### LINKED ISSUE #221: textEffectThickness property: outlineFill is not working.
For the textEffectThickness property of the "Text" entity,
The value "outlineFill" does't work (but "none" "outline" "shadow" work fine.)

It seems to be incorrect in the c++ side
while the doc refer to "outlineFill", the code seems to refer to "outline fill".

### PR DESCRIPTION
**Pull request by HifiExperiments**
fix #221 resolve #206 

Adds an alignment property to text entities that can be “left” (default), “right”, or “center”.

Test plan:
- Create a text entity with text that spans multiple lines with spaces and various characters
- In Create, confirm that all three alignment options work as expected
- Verify that they still work with effects, different margins, when you resize the entity, etc

### CODE REVIEW

File: libraries/render-utils/src/text/Font.cpp [hunk 1]
```diff
@@ -347,38 +359,8 @@ void Font::buildVertices(Font::DrawInfo& drawInfo, const QString& str, const glm
...
-                indices[0] = verticesOffset + 0;
-                indices[1] = verticesOffset + 1;
-                indices[2] = verticesOffset + 2;
-                indices[3] = verticesOffset + 2;
-                indices[4] = verticesOffset + 1;
-                indices[5] = verticesOffset + 3;
-                drawInfo.indicesBuffer->append(sizeof(indices), (const gpu::Byte*)indices);
-                drawInfo.indexCount += NUMBER_OF_INDICES_PER_QUAD;
+
+                glyphsAndCorners.emplace_back(glyph, advance - glm::vec2(0.0f, _ascent));
```
Comment (HifiExperiments) [inline libraries/render-utils/src/text/Font.cpp:363]: we don’t know how long a line will be until we finish looping over all the characters.  so, we first build all the glyph/position pairs in the same way as before

File: libraries/render-utils/src/text/Font.cpp [hunk 2]
```diff
@@ -388,10 +370,71 @@ void Font::buildVertices(Font::DrawInfo& drawInfo, const QString& str, const glm
             advance.x += _spaceWidth;
         }
     }
+
+    std::vector<QuadBuilder> quadBuilders;
+    quadBuilders.reserve(glyphsAndCorners.size());
+    {
+        int i = glyphsAndCorners.size() - 1;
+        while (i >= 0) {
```
Comment (HifiExperiments) [inline libraries/render-utils/src/text/Font.cpp:378]: then, we loop over all the pairs backwards.  we take the first Glyph (the end of the line), use it to compute the spacing on the right, then adjust all of the characters on the line appropriately.  this will build a list of QuadBuilders in reverse order.  we detect when we go to a previous line to recalculate the right spacing

**Comment by digisomni** [comment]
This will be nice and handy for informative UI elements in the world.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-610a0c1.tar_4d1c38c1.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-610a0c1.tar_4d1c38c1.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-610a0c1_4d1c38c1.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-610a0c1_4d1c38c1.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-610a0c1_4d1c38c1.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-Quest-Alpha-PR1020-610a0c1_4d1c38c1.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-610a0c1_4d1c38c1.apk

**Comment by SilverfishVR** [comment]
Testing [Vircadia-PR1020-4d1c38c1](https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-610a0c1_4d1c38c1.exe) on Windows
Erm, the Properties page is empty, same for all entities!
Screenshot 2021-02-12 01 08 13

**Comment by daleglass** [comment]
@SilverfishVR  Any errors on the console?

**Comment by SilverfishVR** [comment]
`[02/12 01:22:27] [WARNING] [default] qrc:/qml/controls/+webengine/FlickableWebViewCore.qml:21:5: Unable to assign [undefined] to bool`

`[02/12 01:22:27] [DEBUG] [qml] [FlickableWebViewCore.qml] Web Entity JS message: file:///C:/Program%20Files/Vircadia%20-%20PR1020/scripts/system/create/entityProperties/html/js/entityProperties.js 252 Uncaught SyntaxError: Unexpected token :`

`[02/12 01:22:27] [DEBUG] [qml] [FlickableWebViewCore.qml] Web Entity JS message: file:///C:/Program%20Files/Vircadia%20-%20PR1020/scripts/system/create/entityProperties/html/entityProperties.html 34 Uncaught ReferenceError: loaded is not defined`

**Comment by daleglass** [comment]
Oh, I think I got it!

File: scripts/system/create/entityProperties/html/js/entityProperties.js [hunk 3]
```diff
@@ -240,6 +240,15 @@ const GROUPS = [
...
             {
+                label: "Alignment",
+                type: "dropdown",
+                options: {
+                    left: "Left",
+                    center: "Center",
+                    right: "Right"
+                },
+                propertyID: "textAlignment",
+            },
```
Comment (daleglass) [inline scripts/system/create/entityProperties/html/js/entityProperties.js:251]: There's a `{` missing after this line.

**Review by daleglass — CHANGES_REQUESTED** [review]

File: scripts/system/create/entityProperties/html/js/entityProperties.js (hunk 3 above)
Comment (HifiExperiments) [reply scripts/system/create/entityProperties/html/js/entityProperties.js:251]: doh

File: libraries/entities-renderer/src/RenderableTextEntityItem.cpp [hunk 4]
```diff
@@ -324,7 +325,7 @@ void entities::TextPayload::render(RenderArgs* args) {
     glm::vec2 bounds = glm::vec2(dimensions.x - (textRenderable->_leftMargin + textRenderable->_rightMargin), dimensions.y - (textRenderable->_topMargin + textRenderable->_bottomMargin));
     textRenderer->draw(batch, textRenderable->_leftMargin / scale, -textRenderable->_topMargin / scale, bounds / scale, scale,
                        textRenderable->_text, textRenderable->_font, textColor, effectColor, textRenderable->_effectThickness, textRenderable->_effect,
-                       textRenderable->_unlit, forward);
+                       textRenderable->_alignment, textRenderable->_unlit, forward);
```
[the remark this answers is not in the document]
Comment (HifiExperiments) [reply libraries/entities-renderer/src/RenderableTextEntityItem.cpp:328]: the number of things has definitely grown since we started adding more effects to text, and it all does need to get passed down through several classes/function calls, but I don't think we need to do this right now

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-c3a01e6.tar_f46f1b22.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-c3a01e6.tar_f46f1b22.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-c3a01e6_f46f1b22.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-c3a01e6_f46f1b22.dmg

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-c3a01e6_f46f1b22.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-Quest-Alpha-PR1020-c3a01e6_f46f1b22.apk

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-c3a01e6_f46f1b22.exe

**Review by daleglass — APPROVED** [review]

**Comment by SilverfishVR** [comment]
Testing [PR1020-c3a01e6](https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-c3a01e6_f46f1b22.exel)

Changing the Alignment property on a text entity does not do anything and the dropdown returns to blank when reopening the create menu. Exported json of a text entity does not have an alignment property, however, adding it manually to the json (`"alignment": "center"`)and reimporting does work for all 3 types

Screenshot 2021-02-12 181345

Exporting an entity made this way does include the alignment property, unless it is "left".

when changing to the properties page (regardless of entity type) I get: 
```
[02/12 18:17:03] [WARNING] [default] qrc:/qml/controls/+webengine/FlickableWebViewCore.qml:21:5: Unable to assign [undefined] to bool
[02/12 18:17:03] [DEBUG] [hifi.scriptengine.module] ScriptEngine::require( "./assets/data/createAppTooltips.json" )
[02/12 18:17:03] [DEBUG] [hifi.scriptengine.module] newModule "file:///C:/Program Files/Vircadia - PR1020/scripts/system/create/modules/createWindow.js"
[02/12 18:17:03] [DEBUG] [hifi.scriptengine.module] "file:///C:/Program Files/Vircadia - PR1020/scripts/system/create/assets/data/createAppTooltips.json"  updating parent.children[ 0 ] = module
[02/12 18:17:03] [DEBUG] [hifi.scriptengine.module] require.fetchModuleSource:  "createAppTooltips.json" QThread(0x2a844214cb0, name = "js:defaultScripts.js")
[02/12 18:17:03] [DEBUG] [hifi.scriptengine] Found script in cache: "createAppTooltips.json"
[02/12 18:17:03] [DEBUG] [hifi.scriptengine.module] "require.instantiateModule: createAppTooltips.json / 28029 bytes"
[02/12 18:17:03] [DEBUG] [hifi.scriptengine.module] ... parsing as JSON
[02/12 18:17:03] [WARNING] [hifi.scriptengine.module] -- result.isError -- "Error: Unable to parse JSON string"
[02/12 18:17:03] [CRITICAL] [hifi.scriptengine] [defaultScripts.js] Call to CallableEvent callback failed!
[02/12 18:17:03] [DEBUG] [qml] [FlickableWebViewCore.qml] Web Entity JS message: file:///C:/Program%20Files/Vircadia%20-%20PR1020/scripts/system/create/entityProperties/html/js/entityProperties.js 2745 Uncaught TypeError: Cannot read property 'updateMinMax' of undefined
```

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-bbbdb8d.tar_515ee408.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-bbbdb8d.tar_515ee408.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-bbbdb8d_515ee408.sh

**build (macOS-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-bbbdb8d_515ee408.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-bbbdb8d_515ee408.exe

**build (ubuntu-18.04, android)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-Quest-Alpha-PR1020-bbbdb8d_515ee408.apk
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-bbbdb8d_515ee408.apk

**Comment by SilverfishVR** [comment]
testing [PR1020-bbbdb8d](https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1020/Vircadia-PR1020-bbbdb8d_515ee408.exe) :
I seem to have run out of things to complain about, it all works as expected now and it will be a nice addition 👍 👍 👍

**Comment by Aitolda** [comment]
It seems to work quite well, but I did noticing something a bit curious that's probably less of a bug and more of a side effect of how this works, but adjusting the top and right margins results in the text sliding smoothly in realtime,, but adjust the bottom or left margin it sort of snaps rather than slides.  This does NOT change the outcome at all, so it' not a problem.
